FROM postgres:alpine3.14
COPY create-databases.sh /docker-entrypoint-initdb.d/
#/docker-entrypoint-initdb.d é uma pasta, qualquer script do Postgres que eu criar irá salvar lá após executar o Postgres